import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";
import NavBarSide from "@/components/NavBarSide";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import TopLeftImg from "@/components/topLeftImg";
import { AnimatePresence, motion } from "framer-motion";
import Transition from "@/components/Transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div
          className={`page bg-site bg-blue-400 text-white bg-cover bg-no-repeat relative`}
        >
          <Layout></Layout>
          {children}
        </div>
      </body>
    </html>
  );
}
